# Generated by Django 3.0.6 on 2020-05-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SKE_CONTESTS', '0007_contesttasktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTaskSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.UUIDField(default=uuid.uuid4)),
                ('date_submit', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField(choices=[(0, 'NIE SPRAWDZONO'), (1, 'BŁĄD SPRAWDZANIA'), (2, 'CAŁKOWICIE BŁĘDNE'), (3, 'CZĘŚCIOWO BŁĘDNE'), (4, 'POPRAWNE')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.ContestTask')),
            ],
        ),
        migrations.CreateModel(
            name='ContestTaskSubmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(choices=[(0, 'NIE SPRAWDZONO'), (1, 'BŁĄD SPRAWDZANIA'), (2, 'TIME_LIMIT'), (3, 'ZLA_ODPOWIEDZ'), (4, 'POPRAWNE')], default=0)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.ContestTaskSubmission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.ContestTaskTest')),
            ],
        ),
    ]
